### PR TITLE
Don’t crash when using find view in tab that’s not an editor

### LINKED ISSUE #998: Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null
*@rsese edit to add repro steps /cc https://github.com/atom/find-and-replace/issues/998#issuecomment-378643806*

1. Open atom/atom `atom --safe .`
2. `Find and Replace: Show`
3. Enable `Only in Selection` 
4. `Project Find: Show`
5. Search for `aa` and run the search
6. While still in the Project Find Results, run`Find and Replace: Show`
7. Run a search

---

_From @joshvera on March 7, 2018 18:56_

[Enter steps to reproduce:]

1. Start a project search in a very large repository.
2. Start another project search while that project search is running.

**Atom**: 1.25.0-beta2 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:101

TypeError: Cannot read property 'getSelectedBufferRange' of null
    at BufferSearch.search (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:101:76)
    at FindView.liveSearch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:356:31)
    at findEditor.onDidStopChanging (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:291:56)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1773:26)
    at later (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -0:25.4.0 core:copy (input.hidden-input)
     -0:25.1.0 project-find:show (input.hidden-input)
     -0:24.8.0 core:paste (input.hidden-input)
     -0:24.3.0 core:confirm (input.hidden-input)
     -0:21 core:copy (input.hidden-input)
     -0:20.7.0 project-find:show (input.hidden-input)
     -0:20.6.0 core:paste (input.hidden-input)
     -0:20.3.0 core:confirm (input.hidden-input)
     -0:14.7.0 core:copy (input.hidden-input)
     -0:14.4.0 project-find:show (input.hidden-input)
     -0:14.2.0 core:paste (input.hidden-input)
     -0:13.9.0 core:confirm (input.hidden-input)
     -0:07.1.0 core:copy (input.hidden-input)
     -0:06.8.0 find-and-replace:show (input.hidden-input)
     -0:06.6.0 core:paste (input.hidden-input)
     -0:06.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

This happens in safe mode.

_Copied from original issue: atom/atom#16898_

### PR DESCRIPTION
**Pull request by ariasuni**
### Description of the Change

- Checks for the presence of an editor before trying to search text.
- Make find and find all buttons disabled when their feature is not available and add an helpful tooltip on them.

### Alternate Designs

It is implement in `buffer-search.js` because filters need to be updated, and stopping the search in `find-view.js` would prevent that.

### Benefits

The fact that now the buttons are disabled and provide a hint of why it is disabled will help people understand why the find/find all feature is unavailable here.

### Possible Drawbacks

I can’t see any.

### Applicable Issues

Fix #998 

---

I think these changes need unit tests but I find it more difficult to find what should go where and how to implement these tests properly, so any help to get started is appreciated.

Also during my work, I found that I was able make filters unmodifiable (i.e. clicking filters did nothing) when pane was opened on a non-editor page, so that will need to be tested too.

### CODE REVIEW

**Comment by ariasuni** [comment]
I spotted several bugs introduced by my changes:

- When opening for the first time on a non-editor page (e.g. Settings), the Find field does not display “No results”. Found thanks to automated tests.
- When opened on a non-editor page, filters can’t be changed. This case lacks automated tests.

**Comment by ariasuni** [comment]
I don’t understand why those tests don’t work, because the behavior they describe is not what I get by doing by hand what the test describe with stable find-and-replace, so I don’t even know what code path give this result.

**Comment by rsese** [comment]
Thanks so much for for opening this pull request @ariasuni ✨

> I think these changes need unit tests but I find it more difficult to find what should go where and how to implement these tests properly, so any help to get started is appreciated.

...

> I don’t understand why those tests don’t work, because the behavior they describe is not what I get by doing by hand what the test describe with stable find-and-replace, so I don’t even know what code path give this result.

Though it's possible someone might jump in with suggestions here, the best place to get help with testing questions is the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638) - not sure if you're on there already, but you can request an invite as detailed in the link.

File: spec/find-view-spec.js [hunk 1]
```diff
@@ -1835,7 +1835,19 @@ describe("FindView", () => {
 
       findView.findEditor.setText("items");
       atom.commands.dispatch(findView.findEditor.element, "find-and-replace:toggle-regex-option");
-      expect(findView.refs.descriptionLabel.textContent).toContain("No results");
+      expect(findView.model.getFindOptions().useRegex).toBe(true);
+      expect(findView.refs.descriptionLabel.textContent).toContain("no results");
```
Comment (lee-dohm) [inline spec/find-view-spec.js]: You changed the case of `No` to `no`. This appears to be why this test (and the other one below) is failing:

```
FindView
  when no buffer is open
    it toggles regex via an event and finds text matching the pattern
      Expected 'No results found for 'items'' to contain 'no results'.
    it toggles selection via an event and finds text matching the pattern
      Expected 'No results found for 'items'' to contain 'no results'.
```

See the lines that start with `Expected` to see what part of the test is failing.

**Comment by ariasuni** [comment]
I guess it’s good now.

**Comment by rsese** [comment]
Thanks @ariasuni :bow:  We can't promise a specific timeframe for when this will be reviewed but we'll ask the team to take a look.
