### PR TITLE
:bug: Fix #496 - Option buttons shouldn't move away from valid match.

### LINKED ISSUE #496: Options buttons move to next result
If I toggle the options buttons to the right in the find and replace box, the selection goes to the next occurrence. It seems to happen with all the four buttons (Regex, Case Sensitive/Insensitive, Within Current Selection, Whole Word). Atom version is 1.0.7.

### PR DESCRIPTION
**Pull request by colllin**
This is a proposal to fix #496.

The problem
---
Toggling the option buttons will jump you away from a selection that already matched the new settings.

The previous behavior
---
Always jump to the next match after the cursor whenever a find option is toggled.

The new behavior
---
Only jump to the next match **if none of the existing selections match** the pattern.  Inversely, **if any of the existing selections match** the pattern, it will not jump you to the next match.

Alternatives
---
I also considered and decided against these possible behaviors:

- Jump to the next match **if any of the existing selections don't match** the pattern.  Inversely, do not jump to the next match **if all of the existing selections match** the pattern.
- When a find option is toggled, destroy any selections that don't match.  If there are any remaining selections, don't jump to the next match.  Otherwise jump to the next match.

### CODE REVIEW

**Comment by colllin** [comment]
Screen captures...

Before: always jumps even if existing selection already matched.
before

After: doesn't jump if existing selection matches.
after-nojump

After: jumps if existing selection doesn't match.
after-jump

**Comment by 50Wliu** [comment]
I like this.  Refs #298.

File: lib/find-view.coffee [hunk 1]
```diff
@@ -447,21 +447,30 @@ class FindView extends View
     else
       optionButton.removeClass 'selected'
 
+  anySelectionsMatchFindPattern: =>
+    editor = @model.getEditor()
+    selections = editor?.getSelections() or []
+    _.any selections, (selection) =>
+      selectionMatchesFindPattern = false
+      editor.scanInBufferRange @model.getFindPatternRegex(), selection.getBufferRange(), ({range}) ->
```
Comment (benogle) [inline lib/find-view.coffee]: This scan seems unnecessary. The model should know if there is a current result marker IIRC. Seems like we should just be able make the decision based on the existence of the current result marker.

**Comment by benogle** [comment]
I'm down with this functionality. Need someone to look over all the code still though.

File: lib/find-view.coffee [hunk 2]
```diff
@@ -447,21 +447,27 @@ class FindView extends View
     else
       optionButton.removeClass 'selected'
 
+  anyMarkersAreSelected: =>
+    selections = @model.getEditor()?.getSelections() or []
+    _.any selections, (selection) =>
+      _.any @model.markers or [], (marker) =>
+        _.isEqual(marker.getBufferRange(), selection.getBufferRange())
```
Comment (benogle) [inline lib/find-view.coffee]: I'm not keen on the underscore usage here. If there are a ton of markers this will probably break down. @maxbrunsfeld  @nathansobo is there a nice way to check if any markers are selected?

Comment (maxbrunsfeld) [inline lib/find-view.coffee]: @colllin I think that we need to avoid a `selections.length x markers.length` loop here, mainly because there can be hundreds of thousands of markers. I think the performance will be more predictable if you query for the markers by range, using `TextEditor::findMarkers`. There is already code to do this in [`BufferSearch.prototype.findMarker`](https://github.com/atom/find-and-replace/blob/d719c79b358cf59e15ca185091965d29a9ead49b/lib/buffer-search.coffee#L194). You could use that method like this:

```coffee
for selectedRange in @model.getEditor().getSelectedBufferRanges()
  if @model.findMarker(selectedRange)
    return true
```

File: spec/find-view-spec.coffee [hunk 3]
```diff
@@ -844,6 +844,37 @@ describe 'FindView', ->
           atom.commands.dispatch(findView.findEditor.element, 'core:confirm')
           expect(findView.descriptionLabel).toHaveClass 'text-error'
 
+      describe "when there are existing selections", ->
+        describe "when any existing selections match the pattern", ->
+          it "shouldn't jump to the next match when toggled on", ->
```
Comment (maxbrunsfeld) [inline spec/find-view-spec.coffee]: Usually we avoid the `should` phrasing in the specs, opting for the slightly more direct `it "does not jump to the next match when toggled on"`.

File: spec/find-view-spec.coffee [hunk 4]
```diff
@@ -892,6 +956,39 @@ describe 'FindView', ->
...
+
+          it "should jump to the next match when toggled off", ->
+            # It's impossible to create a test where `caseSensitive: true` matches but `caseSensitive: false` doesn't.
+            # Instead we'll create a generic selection and ensure that it jumps to the next match.
+            findView.model.setFindOptions caseSensitive: true
+            findView.findEditor.setText 'WORDs'
+            editor.setSelectedBufferRange [[0, 0], [0, 5]]
+            findView.caseOptionButton.click()
+            expect(editor.getSelectedBufferRange()).toEqual [[1, 0], [1, 5]]
+
```
Comment (maxbrunsfeld) [inline spec/find-view-spec.coffee]: I usually don't say this, but I think there might be a few *too* many tests for this code change. They look very good, but I would probably combine the tests for `when toggled on` and `when toggled off` into one, in which you click the button twice, and check that the selection persists at every stage.

**Comment by maxbrunsfeld** [comment]
Thanks for figuring this stuff out @colllin. I left a few suggested changes, but overall this looks great.

**Comment by colllin** [comment]
Thank you for the suggestions and the tip about `Array.prototype.some`.

I...
- changed the `anyMarkersAreSelected` logic to use `BufferSearch.prototype.findMarker`
- combined the toggled on/off tests
- changed the spec phrasing to avoid "should"

**Comment by maxbrunsfeld** [comment]
This is a great PR, @colllin. Thanks so much for sticking with it.

**Comment by maxbrunsfeld** [comment]
This will be in Atom 1.4.0 and 1.4.0-beta0.
